version: '2'

services:
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
  web:
    build: .
    volumes:
      - '.:/code'
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - redis

volumes:
  redisdata:
  .: